/*
Credoxa Audit API

Public API contract for the Credoxa Audit service.  Authentication is provider-neutral. Consumers present an external bearer credential which is verified by the configured authentication adapter before Credoxa Audit establishes tenant/platform, actor, and capability authority.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaaudit

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the IntegrityRangeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrityRangeResponse{}

// IntegrityRangeResponse struct for IntegrityRangeResponse
type IntegrityRangeResponse struct {
	Data      IntegrityRangeResult `json:"data"`
	RequestId string               `json:"request_id"`
}

type _IntegrityRangeResponse IntegrityRangeResponse

// NewIntegrityRangeResponse instantiates a new IntegrityRangeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrityRangeResponse(data IntegrityRangeResult, requestId string) *IntegrityRangeResponse {
	this := IntegrityRangeResponse{}
	this.Data = data
	this.RequestId = requestId
	return &this
}

// NewIntegrityRangeResponseWithDefaults instantiates a new IntegrityRangeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrityRangeResponseWithDefaults() *IntegrityRangeResponse {
	this := IntegrityRangeResponse{}
	return &this
}

// GetData returns the Data field value
func (o *IntegrityRangeResponse) GetData() IntegrityRangeResult {
	if o == nil {
		var ret IntegrityRangeResult
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *IntegrityRangeResponse) GetDataOk() (*IntegrityRangeResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *IntegrityRangeResponse) SetData(v IntegrityRangeResult) {
	o.Data = v
}

// GetRequestId returns the RequestId field value
func (o *IntegrityRangeResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *IntegrityRangeResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *IntegrityRangeResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o IntegrityRangeResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrityRangeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["request_id"] = o.RequestId
	return toSerialize, nil
}

func (o *IntegrityRangeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"request_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntegrityRangeResponse := _IntegrityRangeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIntegrityRangeResponse)

	if err != nil {
		return err
	}

	*o = IntegrityRangeResponse(varIntegrityRangeResponse)

	return err
}

type NullableIntegrityRangeResponse struct {
	value *IntegrityRangeResponse
	isSet bool
}

func (v NullableIntegrityRangeResponse) Get() *IntegrityRangeResponse {
	return v.value
}

func (v *NullableIntegrityRangeResponse) Set(val *IntegrityRangeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrityRangeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrityRangeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrityRangeResponse(val *IntegrityRangeResponse) *NullableIntegrityRangeResponse {
	return &NullableIntegrityRangeResponse{value: val, isSet: true}
}

func (v NullableIntegrityRangeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrityRangeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
