/*
Credoxa Audit API

Public API contract for the Credoxa Audit service.  Authentication is provider-neutral. Consumers present an external bearer credential which is verified by the configured authentication adapter before Credoxa Audit establishes tenant/platform, actor, and capability authority.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaaudit

import (
	"encoding/json"
	"fmt"
)

// RecordVerificationStatus the model 'RecordVerificationStatus'
type RecordVerificationStatus string

// List of RecordVerificationStatus
const (
	RECORDVERIFICATIONSTATUS_VALID                              RecordVerificationStatus = "VALID"
	RECORDVERIFICATIONSTATUS_RECORD_MISSING                     RecordVerificationStatus = "RECORD_MISSING"
	RECORDVERIFICATIONSTATUS_INTEGRITY_ENTRY_MISSING            RecordVerificationStatus = "INTEGRITY_ENTRY_MISSING"
	RECORDVERIFICATIONSTATUS_DOMAIN_MISMATCH                    RecordVerificationStatus = "DOMAIN_MISMATCH"
	RECORDVERIFICATIONSTATUS_RECORD_ID_MISMATCH                 RecordVerificationStatus = "RECORD_ID_MISMATCH"
	RECORDVERIFICATIONSTATUS_UNSUPPORTED_REPRESENTATION_VERSION RecordVerificationStatus = "UNSUPPORTED_REPRESENTATION_VERSION"
	RECORDVERIFICATIONSTATUS_UNSUPPORTED_DIGEST_ALGORITHM       RecordVerificationStatus = "UNSUPPORTED_DIGEST_ALGORITHM"
	RECORDVERIFICATIONSTATUS_RECORD_CANONICALIZATION_FAILED     RecordVerificationStatus = "RECORD_CANONICALIZATION_FAILED"
	RECORDVERIFICATIONSTATUS_RECORD_DIGEST_MISMATCH             RecordVerificationStatus = "RECORD_DIGEST_MISMATCH"
)

// All allowed values of RecordVerificationStatus enum
var AllowedRecordVerificationStatusEnumValues = []RecordVerificationStatus{
	"VALID",
	"RECORD_MISSING",
	"INTEGRITY_ENTRY_MISSING",
	"DOMAIN_MISMATCH",
	"RECORD_ID_MISMATCH",
	"UNSUPPORTED_REPRESENTATION_VERSION",
	"UNSUPPORTED_DIGEST_ALGORITHM",
	"RECORD_CANONICALIZATION_FAILED",
	"RECORD_DIGEST_MISMATCH",
}

func (v *RecordVerificationStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RecordVerificationStatus(value)
	for _, existing := range AllowedRecordVerificationStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RecordVerificationStatus", value)
}

// NewRecordVerificationStatusFromValue returns a pointer to a valid RecordVerificationStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRecordVerificationStatusFromValue(v string) (*RecordVerificationStatus, error) {
	ev := RecordVerificationStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RecordVerificationStatus: valid values are %v", v, AllowedRecordVerificationStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RecordVerificationStatus) IsValid() bool {
	for _, existing := range AllowedRecordVerificationStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RecordVerificationStatus value
func (v RecordVerificationStatus) Ptr() *RecordVerificationStatus {
	return &v
}

type NullableRecordVerificationStatus struct {
	value *RecordVerificationStatus
	isSet bool
}

func (v NullableRecordVerificationStatus) Get() *RecordVerificationStatus {
	return v.value
}

func (v *NullableRecordVerificationStatus) Set(val *RecordVerificationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordVerificationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordVerificationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordVerificationStatus(val *RecordVerificationStatus) *NullableRecordVerificationStatus {
	return &NullableRecordVerificationStatus{value: val, isSet: true}
}

func (v NullableRecordVerificationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordVerificationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
