/*
Credoxa Audit API

Public API contract for the Credoxa Audit service.  Authentication is provider-neutral. Consumers present an external bearer credential which is verified by the configured authentication adapter before Credoxa Audit establishes tenant/platform, actor, and capability authority.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaaudit

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AuditRecordPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditRecordPage{}

// AuditRecordPage struct for AuditRecordPage
type AuditRecordPage struct {
	Records    []AuditRecord  `json:"records"`
	NextCursor NullableString `json:"next_cursor"`
}

type _AuditRecordPage AuditRecordPage

// NewAuditRecordPage instantiates a new AuditRecordPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditRecordPage(records []AuditRecord, nextCursor NullableString) *AuditRecordPage {
	this := AuditRecordPage{}
	this.Records = records
	this.NextCursor = nextCursor
	return &this
}

// NewAuditRecordPageWithDefaults instantiates a new AuditRecordPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditRecordPageWithDefaults() *AuditRecordPage {
	this := AuditRecordPage{}
	return &this
}

// GetRecords returns the Records field value
func (o *AuditRecordPage) GetRecords() []AuditRecord {
	if o == nil {
		var ret []AuditRecord
		return ret
	}

	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value
// and a boolean to check if the value has been set.
func (o *AuditRecordPage) GetRecordsOk() ([]AuditRecord, bool) {
	if o == nil {
		return nil, false
	}
	return o.Records, true
}

// SetRecords sets field value
func (o *AuditRecordPage) SetRecords(v []AuditRecord) {
	o.Records = v
}

// GetNextCursor returns the NextCursor field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AuditRecordPage) GetNextCursor() string {
	if o == nil || o.NextCursor.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditRecordPage) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// SetNextCursor sets field value
func (o *AuditRecordPage) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

func (o AuditRecordPage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditRecordPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["records"] = o.Records
	toSerialize["next_cursor"] = o.NextCursor.Get()
	return toSerialize, nil
}

func (o *AuditRecordPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"records",
		"next_cursor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuditRecordPage := _AuditRecordPage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuditRecordPage)

	if err != nil {
		return err
	}

	*o = AuditRecordPage(varAuditRecordPage)

	return err
}

type NullableAuditRecordPage struct {
	value *AuditRecordPage
	isSet bool
}

func (v NullableAuditRecordPage) Get() *AuditRecordPage {
	return v.value
}

func (v *NullableAuditRecordPage) Set(val *AuditRecordPage) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditRecordPage) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditRecordPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditRecordPage(val *AuditRecordPage) *NullableAuditRecordPage {
	return &NullableAuditRecordPage{value: val, isSet: true}
}

func (v NullableAuditRecordPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditRecordPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
