/*
Credoxa Audit API

Public API contract for the Credoxa Audit service.  Authentication is provider-neutral. Consumers present an external bearer credential which is verified by the configured authentication adapter before Credoxa Audit establishes tenant/platform, actor, and capability authority.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaaudit

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the PublishAuditEventRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishAuditEventRequest{}

// PublishAuditEventRequest struct for PublishAuditEventRequest
type PublishAuditEventRequest struct {
	EventId       string                  `json:"event_id" validate:"regexp=^[A-Za-z0-9][A-Za-z0-9._:-]{0,254}$"`
	OccurredAt    time.Time               `json:"occurred_at"`
	Action        string                  `json:"action" validate:"regexp=^[A-Za-z0-9]+(?:[._:-][A-Za-z0-9]+)*$"`
	Outcome       AuditOutcome            `json:"outcome"`
	Target        NullableAuditTarget     `json:"target,omitempty"`
	Metadata      map[string]interface{}  `json:"metadata,omitempty"`
	Provenance    NullableAuditProvenance `json:"provenance,omitempty"`
	CorrelationId NullableString          `json:"correlation_id,omitempty" validate:"regexp=^[A-Za-z0-9][A-Za-z0-9._:-]{0,254}$"`
}

type _PublishAuditEventRequest PublishAuditEventRequest

// NewPublishAuditEventRequest instantiates a new PublishAuditEventRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishAuditEventRequest(eventId string, occurredAt time.Time, action string, outcome AuditOutcome) *PublishAuditEventRequest {
	this := PublishAuditEventRequest{}
	this.EventId = eventId
	this.OccurredAt = occurredAt
	this.Action = action
	this.Outcome = outcome
	return &this
}

// NewPublishAuditEventRequestWithDefaults instantiates a new PublishAuditEventRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishAuditEventRequestWithDefaults() *PublishAuditEventRequest {
	this := PublishAuditEventRequest{}
	return &this
}

// GetEventId returns the EventId field value
func (o *PublishAuditEventRequest) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *PublishAuditEventRequest) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *PublishAuditEventRequest) SetEventId(v string) {
	o.EventId = v
}

// GetOccurredAt returns the OccurredAt field value
func (o *PublishAuditEventRequest) GetOccurredAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.OccurredAt
}

// GetOccurredAtOk returns a tuple with the OccurredAt field value
// and a boolean to check if the value has been set.
func (o *PublishAuditEventRequest) GetOccurredAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OccurredAt, true
}

// SetOccurredAt sets field value
func (o *PublishAuditEventRequest) SetOccurredAt(v time.Time) {
	o.OccurredAt = v
}

// GetAction returns the Action field value
func (o *PublishAuditEventRequest) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *PublishAuditEventRequest) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *PublishAuditEventRequest) SetAction(v string) {
	o.Action = v
}

// GetOutcome returns the Outcome field value
func (o *PublishAuditEventRequest) GetOutcome() AuditOutcome {
	if o == nil {
		var ret AuditOutcome
		return ret
	}

	return o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value
// and a boolean to check if the value has been set.
func (o *PublishAuditEventRequest) GetOutcomeOk() (*AuditOutcome, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outcome, true
}

// SetOutcome sets field value
func (o *PublishAuditEventRequest) SetOutcome(v AuditOutcome) {
	o.Outcome = v
}

// GetTarget returns the Target field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublishAuditEventRequest) GetTarget() AuditTarget {
	if o == nil || IsNil(o.Target.Get()) {
		var ret AuditTarget
		return ret
	}
	return *o.Target.Get()
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublishAuditEventRequest) GetTargetOk() (*AuditTarget, bool) {
	if o == nil {
		return nil, false
	}
	return o.Target.Get(), o.Target.IsSet()
}

// HasTarget returns a boolean if a field has been set.
func (o *PublishAuditEventRequest) HasTarget() bool {
	if o != nil && o.Target.IsSet() {
		return true
	}

	return false
}

// SetTarget gets a reference to the given NullableAuditTarget and assigns it to the Target field.
func (o *PublishAuditEventRequest) SetTarget(v AuditTarget) {
	o.Target.Set(&v)
}

// SetTargetNil sets the value for Target to be an explicit nil
func (o *PublishAuditEventRequest) SetTargetNil() {
	o.Target.Set(nil)
}

// UnsetTarget ensures that no value is present for Target, not even an explicit nil
func (o *PublishAuditEventRequest) UnsetTarget() {
	o.Target.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublishAuditEventRequest) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublishAuditEventRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *PublishAuditEventRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *PublishAuditEventRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetProvenance returns the Provenance field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublishAuditEventRequest) GetProvenance() AuditProvenance {
	if o == nil || IsNil(o.Provenance.Get()) {
		var ret AuditProvenance
		return ret
	}
	return *o.Provenance.Get()
}

// GetProvenanceOk returns a tuple with the Provenance field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublishAuditEventRequest) GetProvenanceOk() (*AuditProvenance, bool) {
	if o == nil {
		return nil, false
	}
	return o.Provenance.Get(), o.Provenance.IsSet()
}

// HasProvenance returns a boolean if a field has been set.
func (o *PublishAuditEventRequest) HasProvenance() bool {
	if o != nil && o.Provenance.IsSet() {
		return true
	}

	return false
}

// SetProvenance gets a reference to the given NullableAuditProvenance and assigns it to the Provenance field.
func (o *PublishAuditEventRequest) SetProvenance(v AuditProvenance) {
	o.Provenance.Set(&v)
}

// SetProvenanceNil sets the value for Provenance to be an explicit nil
func (o *PublishAuditEventRequest) SetProvenanceNil() {
	o.Provenance.Set(nil)
}

// UnsetProvenance ensures that no value is present for Provenance, not even an explicit nil
func (o *PublishAuditEventRequest) UnsetProvenance() {
	o.Provenance.Unset()
}

// GetCorrelationId returns the CorrelationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublishAuditEventRequest) GetCorrelationId() string {
	if o == nil || IsNil(o.CorrelationId.Get()) {
		var ret string
		return ret
	}
	return *o.CorrelationId.Get()
}

// GetCorrelationIdOk returns a tuple with the CorrelationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublishAuditEventRequest) GetCorrelationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CorrelationId.Get(), o.CorrelationId.IsSet()
}

// HasCorrelationId returns a boolean if a field has been set.
func (o *PublishAuditEventRequest) HasCorrelationId() bool {
	if o != nil && o.CorrelationId.IsSet() {
		return true
	}

	return false
}

// SetCorrelationId gets a reference to the given NullableString and assigns it to the CorrelationId field.
func (o *PublishAuditEventRequest) SetCorrelationId(v string) {
	o.CorrelationId.Set(&v)
}

// SetCorrelationIdNil sets the value for CorrelationId to be an explicit nil
func (o *PublishAuditEventRequest) SetCorrelationIdNil() {
	o.CorrelationId.Set(nil)
}

// UnsetCorrelationId ensures that no value is present for CorrelationId, not even an explicit nil
func (o *PublishAuditEventRequest) UnsetCorrelationId() {
	o.CorrelationId.Unset()
}

func (o PublishAuditEventRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishAuditEventRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event_id"] = o.EventId
	toSerialize["occurred_at"] = o.OccurredAt
	toSerialize["action"] = o.Action
	toSerialize["outcome"] = o.Outcome
	if o.Target.IsSet() {
		toSerialize["target"] = o.Target.Get()
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Provenance.IsSet() {
		toSerialize["provenance"] = o.Provenance.Get()
	}
	if o.CorrelationId.IsSet() {
		toSerialize["correlation_id"] = o.CorrelationId.Get()
	}
	return toSerialize, nil
}

func (o *PublishAuditEventRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_id",
		"occurred_at",
		"action",
		"outcome",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublishAuditEventRequest := _PublishAuditEventRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublishAuditEventRequest)

	if err != nil {
		return err
	}

	*o = PublishAuditEventRequest(varPublishAuditEventRequest)

	return err
}

type NullablePublishAuditEventRequest struct {
	value *PublishAuditEventRequest
	isSet bool
}

func (v NullablePublishAuditEventRequest) Get() *PublishAuditEventRequest {
	return v.value
}

func (v *NullablePublishAuditEventRequest) Set(val *PublishAuditEventRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishAuditEventRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishAuditEventRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishAuditEventRequest(val *PublishAuditEventRequest) *NullablePublishAuditEventRequest {
	return &NullablePublishAuditEventRequest{value: val, isSet: true}
}

func (v NullablePublishAuditEventRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishAuditEventRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
