/*
Credoxa Audit API

Public API contract for the Credoxa Audit service.  Authentication is provider-neutral. Consumers present an external bearer credential which is verified by the configured authentication adapter before Credoxa Audit establishes tenant/platform, actor, and capability authority.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaaudit

import (
	"encoding/json"
	"fmt"
)

// IntegrityPositionStatus the model 'IntegrityPositionStatus'
type IntegrityPositionStatus string

// List of IntegrityPositionStatus
const (
	INTEGRITYPOSITIONSTATUS_PRESENT_VALID                  IntegrityPositionStatus = "PRESENT_VALID"
	INTEGRITYPOSITIONSTATUS_PRESENT_TAMPERED               IntegrityPositionStatus = "PRESENT_TAMPERED"
	INTEGRITYPOSITIONSTATUS_MISSING_AUTHORIZED_DISPOSITION IntegrityPositionStatus = "MISSING_AUTHORIZED_DISPOSITION"
	INTEGRITYPOSITIONSTATUS_MISSING_UNEXPLAINED            IntegrityPositionStatus = "MISSING_UNEXPLAINED"
)

// All allowed values of IntegrityPositionStatus enum
var AllowedIntegrityPositionStatusEnumValues = []IntegrityPositionStatus{
	"PRESENT_VALID",
	"PRESENT_TAMPERED",
	"MISSING_AUTHORIZED_DISPOSITION",
	"MISSING_UNEXPLAINED",
}

func (v *IntegrityPositionStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := IntegrityPositionStatus(value)
	for _, existing := range AllowedIntegrityPositionStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid IntegrityPositionStatus", value)
}

// NewIntegrityPositionStatusFromValue returns a pointer to a valid IntegrityPositionStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewIntegrityPositionStatusFromValue(v string) (*IntegrityPositionStatus, error) {
	ev := IntegrityPositionStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for IntegrityPositionStatus: valid values are %v", v, AllowedIntegrityPositionStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v IntegrityPositionStatus) IsValid() bool {
	for _, existing := range AllowedIntegrityPositionStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to IntegrityPositionStatus value
func (v IntegrityPositionStatus) Ptr() *IntegrityPositionStatus {
	return &v
}

type NullableIntegrityPositionStatus struct {
	value *IntegrityPositionStatus
	isSet bool
}

func (v NullableIntegrityPositionStatus) Get() *IntegrityPositionStatus {
	return v.value
}

func (v *NullableIntegrityPositionStatus) Set(val *IntegrityPositionStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrityPositionStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrityPositionStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrityPositionStatus(val *IntegrityPositionStatus) *NullableIntegrityPositionStatus {
	return &NullableIntegrityPositionStatus{value: val, isSet: true}
}

func (v NullableIntegrityPositionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrityPositionStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
