/*
Credoxa Audit API

Public API contract for the Credoxa Audit service.  Authentication is provider-neutral. Consumers present an external bearer credential which is verified by the configured authentication adapter before Credoxa Audit establishes tenant/platform, actor, and capability authority.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaaudit

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AuditTarget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditTarget{}

// AuditTarget struct for AuditTarget
type AuditTarget struct {
	ResourceType string `json:"resource_type" validate:"regexp=^[A-Za-z0-9]+(?:[._:-][A-Za-z0-9]+)*$"`
	ResourceId   string `json:"resource_id" validate:"regexp=^[A-Za-z0-9][A-Za-z0-9._:-]{0,254}$"`
}

type _AuditTarget AuditTarget

// NewAuditTarget instantiates a new AuditTarget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditTarget(resourceType string, resourceId string) *AuditTarget {
	this := AuditTarget{}
	this.ResourceType = resourceType
	this.ResourceId = resourceId
	return &this
}

// NewAuditTargetWithDefaults instantiates a new AuditTarget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditTargetWithDefaults() *AuditTarget {
	this := AuditTarget{}
	return &this
}

// GetResourceType returns the ResourceType field value
func (o *AuditTarget) GetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *AuditTarget) GetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *AuditTarget) SetResourceType(v string) {
	o.ResourceType = v
}

// GetResourceId returns the ResourceId field value
func (o *AuditTarget) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *AuditTarget) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *AuditTarget) SetResourceId(v string) {
	o.ResourceId = v
}

func (o AuditTarget) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditTarget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resource_type"] = o.ResourceType
	toSerialize["resource_id"] = o.ResourceId
	return toSerialize, nil
}

func (o *AuditTarget) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resource_type",
		"resource_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuditTarget := _AuditTarget{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuditTarget)

	if err != nil {
		return err
	}

	*o = AuditTarget(varAuditTarget)

	return err
}

type NullableAuditTarget struct {
	value *AuditTarget
	isSet bool
}

func (v NullableAuditTarget) Get() *AuditTarget {
	return v.value
}

func (v *NullableAuditTarget) Set(val *AuditTarget) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditTarget) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditTarget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditTarget(val *AuditTarget) *NullableAuditTarget {
	return &NullableAuditTarget{value: val, isSet: true}
}

func (v NullableAuditTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditTarget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
