/*
Credoxa Audit API

Public API contract for the Credoxa Audit service.  Authentication is provider-neutral. Consumers present an external bearer credential which is verified by the configured authentication adapter before Credoxa Audit establishes tenant/platform, actor, and capability authority.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaaudit

import (
	"encoding/json"
	"fmt"
)

// ChainVerificationStatus the model 'ChainVerificationStatus'
type ChainVerificationStatus string

// List of ChainVerificationStatus
const (
	CHAINVERIFICATIONSTATUS_VALID                              ChainVerificationStatus = "VALID"
	CHAINVERIFICATIONSTATUS_EMPTY_RANGE                        ChainVerificationStatus = "EMPTY_RANGE"
	CHAINVERIFICATIONSTATUS_BOUNDARY_MISSING                   ChainVerificationStatus = "BOUNDARY_MISSING"
	CHAINVERIFICATIONSTATUS_SEQUENCE_GAP                       ChainVerificationStatus = "SEQUENCE_GAP"
	CHAINVERIFICATIONSTATUS_DOMAIN_MISMATCH                    ChainVerificationStatus = "DOMAIN_MISMATCH"
	CHAINVERIFICATIONSTATUS_UNSUPPORTED_REPRESENTATION_VERSION ChainVerificationStatus = "UNSUPPORTED_REPRESENTATION_VERSION"
	CHAINVERIFICATIONSTATUS_UNSUPPORTED_DIGEST_ALGORITHM       ChainVerificationStatus = "UNSUPPORTED_DIGEST_ALGORITHM"
	CHAINVERIFICATIONSTATUS_PREVIOUS_DIGEST_MISMATCH           ChainVerificationStatus = "PREVIOUS_DIGEST_MISMATCH"
	CHAINVERIFICATIONSTATUS_CHAIN_DIGEST_MISMATCH              ChainVerificationStatus = "CHAIN_DIGEST_MISMATCH"
)

// All allowed values of ChainVerificationStatus enum
var AllowedChainVerificationStatusEnumValues = []ChainVerificationStatus{
	"VALID",
	"EMPTY_RANGE",
	"BOUNDARY_MISSING",
	"SEQUENCE_GAP",
	"DOMAIN_MISMATCH",
	"UNSUPPORTED_REPRESENTATION_VERSION",
	"UNSUPPORTED_DIGEST_ALGORITHM",
	"PREVIOUS_DIGEST_MISMATCH",
	"CHAIN_DIGEST_MISMATCH",
}

func (v *ChainVerificationStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ChainVerificationStatus(value)
	for _, existing := range AllowedChainVerificationStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ChainVerificationStatus", value)
}

// NewChainVerificationStatusFromValue returns a pointer to a valid ChainVerificationStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewChainVerificationStatusFromValue(v string) (*ChainVerificationStatus, error) {
	ev := ChainVerificationStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ChainVerificationStatus: valid values are %v", v, AllowedChainVerificationStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ChainVerificationStatus) IsValid() bool {
	for _, existing := range AllowedChainVerificationStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ChainVerificationStatus value
func (v ChainVerificationStatus) Ptr() *ChainVerificationStatus {
	return &v
}

type NullableChainVerificationStatus struct {
	value *ChainVerificationStatus
	isSet bool
}

func (v NullableChainVerificationStatus) Get() *ChainVerificationStatus {
	return v.value
}

func (v *NullableChainVerificationStatus) Set(val *ChainVerificationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableChainVerificationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableChainVerificationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChainVerificationStatus(val *ChainVerificationStatus) *NullableChainVerificationStatus {
	return &NullableChainVerificationStatus{value: val, isSet: true}
}

func (v NullableChainVerificationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChainVerificationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
