/*
Credoxa Audit API

Public API contract for the Credoxa Audit service.  Authentication is provider-neutral. Consumers present an external bearer credential which is verified by the configured authentication adapter before Credoxa Audit establishes tenant/platform, actor, and capability authority.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaaudit

import (
	"encoding/json"
	"fmt"
)

// EvidenceContinuityStatus the model 'EvidenceContinuityStatus'
type EvidenceContinuityStatus string

// List of EvidenceContinuityStatus
const (
	EVIDENCECONTINUITYSTATUS_COMPLETE                   EvidenceContinuityStatus = "COMPLETE"
	EVIDENCECONTINUITYSTATUS_AUTHORIZED_DISPOSITIONS    EvidenceContinuityStatus = "AUTHORIZED_DISPOSITIONS"
	EVIDENCECONTINUITYSTATUS_RECORD_INTEGRITY_FAILURE   EvidenceContinuityStatus = "RECORD_INTEGRITY_FAILURE"
	EVIDENCECONTINUITYSTATUS_UNEXPLAINED_RECORD_ABSENCE EvidenceContinuityStatus = "UNEXPLAINED_RECORD_ABSENCE"
)

// All allowed values of EvidenceContinuityStatus enum
var AllowedEvidenceContinuityStatusEnumValues = []EvidenceContinuityStatus{
	"COMPLETE",
	"AUTHORIZED_DISPOSITIONS",
	"RECORD_INTEGRITY_FAILURE",
	"UNEXPLAINED_RECORD_ABSENCE",
}

func (v *EvidenceContinuityStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EvidenceContinuityStatus(value)
	for _, existing := range AllowedEvidenceContinuityStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EvidenceContinuityStatus", value)
}

// NewEvidenceContinuityStatusFromValue returns a pointer to a valid EvidenceContinuityStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEvidenceContinuityStatusFromValue(v string) (*EvidenceContinuityStatus, error) {
	ev := EvidenceContinuityStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EvidenceContinuityStatus: valid values are %v", v, AllowedEvidenceContinuityStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EvidenceContinuityStatus) IsValid() bool {
	for _, existing := range AllowedEvidenceContinuityStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EvidenceContinuityStatus value
func (v EvidenceContinuityStatus) Ptr() *EvidenceContinuityStatus {
	return &v
}

type NullableEvidenceContinuityStatus struct {
	value *EvidenceContinuityStatus
	isSet bool
}

func (v NullableEvidenceContinuityStatus) Get() *EvidenceContinuityStatus {
	return v.value
}

func (v *NullableEvidenceContinuityStatus) Set(val *EvidenceContinuityStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableEvidenceContinuityStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableEvidenceContinuityStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvidenceContinuityStatus(val *EvidenceContinuityStatus) *NullableEvidenceContinuityStatus {
	return &NullableEvidenceContinuityStatus{value: val, isSet: true}
}

func (v NullableEvidenceContinuityStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvidenceContinuityStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
