/*
Credoxa Audit API

Public API contract for the Credoxa Audit service.  Authentication is provider-neutral. Consumers present an external bearer credential which is verified by the configured authentication adapter before Credoxa Audit establishes tenant/platform, actor, and capability authority.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaaudit

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RecordIntegrityResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecordIntegrityResponse{}

// RecordIntegrityResponse struct for RecordIntegrityResponse
type RecordIntegrityResponse struct {
	Data      RecordIntegrityResult `json:"data"`
	RequestId string                `json:"request_id"`
}

type _RecordIntegrityResponse RecordIntegrityResponse

// NewRecordIntegrityResponse instantiates a new RecordIntegrityResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordIntegrityResponse(data RecordIntegrityResult, requestId string) *RecordIntegrityResponse {
	this := RecordIntegrityResponse{}
	this.Data = data
	this.RequestId = requestId
	return &this
}

// NewRecordIntegrityResponseWithDefaults instantiates a new RecordIntegrityResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordIntegrityResponseWithDefaults() *RecordIntegrityResponse {
	this := RecordIntegrityResponse{}
	return &this
}

// GetData returns the Data field value
func (o *RecordIntegrityResponse) GetData() RecordIntegrityResult {
	if o == nil {
		var ret RecordIntegrityResult
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RecordIntegrityResponse) GetDataOk() (*RecordIntegrityResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RecordIntegrityResponse) SetData(v RecordIntegrityResult) {
	o.Data = v
}

// GetRequestId returns the RequestId field value
func (o *RecordIntegrityResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *RecordIntegrityResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *RecordIntegrityResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o RecordIntegrityResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecordIntegrityResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["request_id"] = o.RequestId
	return toSerialize, nil
}

func (o *RecordIntegrityResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"request_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecordIntegrityResponse := _RecordIntegrityResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecordIntegrityResponse)

	if err != nil {
		return err
	}

	*o = RecordIntegrityResponse(varRecordIntegrityResponse)

	return err
}

type NullableRecordIntegrityResponse struct {
	value *RecordIntegrityResponse
	isSet bool
}

func (v NullableRecordIntegrityResponse) Get() *RecordIntegrityResponse {
	return v.value
}

func (v *NullableRecordIntegrityResponse) Set(val *RecordIntegrityResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordIntegrityResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordIntegrityResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordIntegrityResponse(val *RecordIntegrityResponse) *NullableRecordIntegrityResponse {
	return &NullableRecordIntegrityResponse{value: val, isSet: true}
}

func (v NullableRecordIntegrityResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordIntegrityResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
