/*
Credoxa Audit API

Public API contract for the Credoxa Audit service.  Authentication is provider-neutral. Consumers present an external bearer credential which is verified by the configured authentication adapter before Credoxa Audit establishes tenant/platform, actor, and capability authority.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaaudit

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AuditProvenance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditProvenance{}

// AuditProvenance struct for AuditProvenance
type AuditProvenance struct {
	Source string `json:"source" validate:"regexp=^[A-Za-z0-9][A-Za-z0-9._:-]{0,254}$"`
}

type _AuditProvenance AuditProvenance

// NewAuditProvenance instantiates a new AuditProvenance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditProvenance(source string) *AuditProvenance {
	this := AuditProvenance{}
	this.Source = source
	return &this
}

// NewAuditProvenanceWithDefaults instantiates a new AuditProvenance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditProvenanceWithDefaults() *AuditProvenance {
	this := AuditProvenance{}
	return &this
}

// GetSource returns the Source field value
func (o *AuditProvenance) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *AuditProvenance) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *AuditProvenance) SetSource(v string) {
	o.Source = v
}

func (o AuditProvenance) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditProvenance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

func (o *AuditProvenance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuditProvenance := _AuditProvenance{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuditProvenance)

	if err != nil {
		return err
	}

	*o = AuditProvenance(varAuditProvenance)

	return err
}

type NullableAuditProvenance struct {
	value *AuditProvenance
	isSet bool
}

func (v NullableAuditProvenance) Get() *AuditProvenance {
	return v.value
}

func (v *NullableAuditProvenance) Set(val *AuditProvenance) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditProvenance) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditProvenance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditProvenance(val *AuditProvenance) *NullableAuditProvenance {
	return &NullableAuditProvenance{value: val, isSet: true}
}

func (v NullableAuditProvenance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditProvenance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
