/*
Credoxa Audit API

Public API contract for the Credoxa Audit service.  Authentication is provider-neutral. Consumers present an external bearer credential which is verified by the configured authentication adapter before Credoxa Audit establishes tenant/platform, actor, and capability authority.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaaudit

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AuditRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditRecord{}

// AuditRecord struct for AuditRecord
type AuditRecord struct {
	RecordId           string                 `json:"record_id"`
	EventId            string                 `json:"event_id" validate:"regexp=^[A-Za-z0-9][A-Za-z0-9._:-]{0,254}$"`
	OccurredAt         time.Time              `json:"occurred_at"`
	RecordedAt         time.Time              `json:"recorded_at"`
	TenantId           NullableString         `json:"tenant_id"`
	IsPlatform         bool                   `json:"is_platform"`
	ActorId            NullableString         `json:"actor_id"`
	ActorKind          NullableActorKind      `json:"actor_kind"`
	Action             string                 `json:"action" validate:"regexp=^[A-Za-z0-9]+(?:[._:-][A-Za-z0-9]+)*$"`
	Outcome            AuditOutcome           `json:"outcome"`
	TargetResourceType NullableString         `json:"target_resource_type" validate:"regexp=^[A-Za-z0-9]+(?:[._:-][A-Za-z0-9]+)*$"`
	TargetResourceId   NullableString         `json:"target_resource_id" validate:"regexp=^[A-Za-z0-9][A-Za-z0-9._:-]{0,254}$"`
	Metadata           map[string]interface{} `json:"metadata"`
	ProvenanceSource   NullableString         `json:"provenance_source" validate:"regexp=^[A-Za-z0-9][A-Za-z0-9._:-]{0,254}$"`
	CorrelationId      NullableString         `json:"correlation_id" validate:"regexp=^[A-Za-z0-9][A-Za-z0-9._:-]{0,254}$"`
}

type _AuditRecord AuditRecord

// NewAuditRecord instantiates a new AuditRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditRecord(recordId string, eventId string, occurredAt time.Time, recordedAt time.Time, tenantId NullableString, isPlatform bool, actorId NullableString, actorKind NullableActorKind, action string, outcome AuditOutcome, targetResourceType NullableString, targetResourceId NullableString, metadata map[string]interface{}, provenanceSource NullableString, correlationId NullableString) *AuditRecord {
	this := AuditRecord{}
	this.RecordId = recordId
	this.EventId = eventId
	this.OccurredAt = occurredAt
	this.RecordedAt = recordedAt
	this.TenantId = tenantId
	this.IsPlatform = isPlatform
	this.ActorId = actorId
	this.ActorKind = actorKind
	this.Action = action
	this.Outcome = outcome
	this.TargetResourceType = targetResourceType
	this.TargetResourceId = targetResourceId
	this.Metadata = metadata
	this.ProvenanceSource = provenanceSource
	this.CorrelationId = correlationId
	return &this
}

// NewAuditRecordWithDefaults instantiates a new AuditRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditRecordWithDefaults() *AuditRecord {
	this := AuditRecord{}
	return &this
}

// GetRecordId returns the RecordId field value
func (o *AuditRecord) GetRecordId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecordId
}

// GetRecordIdOk returns a tuple with the RecordId field value
// and a boolean to check if the value has been set.
func (o *AuditRecord) GetRecordIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecordId, true
}

// SetRecordId sets field value
func (o *AuditRecord) SetRecordId(v string) {
	o.RecordId = v
}

// GetEventId returns the EventId field value
func (o *AuditRecord) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *AuditRecord) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *AuditRecord) SetEventId(v string) {
	o.EventId = v
}

// GetOccurredAt returns the OccurredAt field value
func (o *AuditRecord) GetOccurredAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.OccurredAt
}

// GetOccurredAtOk returns a tuple with the OccurredAt field value
// and a boolean to check if the value has been set.
func (o *AuditRecord) GetOccurredAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OccurredAt, true
}

// SetOccurredAt sets field value
func (o *AuditRecord) SetOccurredAt(v time.Time) {
	o.OccurredAt = v
}

// GetRecordedAt returns the RecordedAt field value
func (o *AuditRecord) GetRecordedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.RecordedAt
}

// GetRecordedAtOk returns a tuple with the RecordedAt field value
// and a boolean to check if the value has been set.
func (o *AuditRecord) GetRecordedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecordedAt, true
}

// SetRecordedAt sets field value
func (o *AuditRecord) SetRecordedAt(v time.Time) {
	o.RecordedAt = v
}

// GetTenantId returns the TenantId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AuditRecord) GetTenantId() string {
	if o == nil || o.TenantId.Get() == nil {
		var ret string
		return ret
	}

	return *o.TenantId.Get()
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditRecord) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantId.Get(), o.TenantId.IsSet()
}

// SetTenantId sets field value
func (o *AuditRecord) SetTenantId(v string) {
	o.TenantId.Set(&v)
}

// GetIsPlatform returns the IsPlatform field value
func (o *AuditRecord) GetIsPlatform() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPlatform
}

// GetIsPlatformOk returns a tuple with the IsPlatform field value
// and a boolean to check if the value has been set.
func (o *AuditRecord) GetIsPlatformOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPlatform, true
}

// SetIsPlatform sets field value
func (o *AuditRecord) SetIsPlatform(v bool) {
	o.IsPlatform = v
}

// GetActorId returns the ActorId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AuditRecord) GetActorId() string {
	if o == nil || o.ActorId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ActorId.Get()
}

// GetActorIdOk returns a tuple with the ActorId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditRecord) GetActorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActorId.Get(), o.ActorId.IsSet()
}

// SetActorId sets field value
func (o *AuditRecord) SetActorId(v string) {
	o.ActorId.Set(&v)
}

// GetActorKind returns the ActorKind field value
// If the value is explicit nil, the zero value for ActorKind will be returned
func (o *AuditRecord) GetActorKind() ActorKind {
	if o == nil || o.ActorKind.Get() == nil {
		var ret ActorKind
		return ret
	}

	return *o.ActorKind.Get()
}

// GetActorKindOk returns a tuple with the ActorKind field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditRecord) GetActorKindOk() (*ActorKind, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActorKind.Get(), o.ActorKind.IsSet()
}

// SetActorKind sets field value
func (o *AuditRecord) SetActorKind(v ActorKind) {
	o.ActorKind.Set(&v)
}

// GetAction returns the Action field value
func (o *AuditRecord) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *AuditRecord) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *AuditRecord) SetAction(v string) {
	o.Action = v
}

// GetOutcome returns the Outcome field value
func (o *AuditRecord) GetOutcome() AuditOutcome {
	if o == nil {
		var ret AuditOutcome
		return ret
	}

	return o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value
// and a boolean to check if the value has been set.
func (o *AuditRecord) GetOutcomeOk() (*AuditOutcome, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outcome, true
}

// SetOutcome sets field value
func (o *AuditRecord) SetOutcome(v AuditOutcome) {
	o.Outcome = v
}

// GetTargetResourceType returns the TargetResourceType field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AuditRecord) GetTargetResourceType() string {
	if o == nil || o.TargetResourceType.Get() == nil {
		var ret string
		return ret
	}

	return *o.TargetResourceType.Get()
}

// GetTargetResourceTypeOk returns a tuple with the TargetResourceType field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditRecord) GetTargetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TargetResourceType.Get(), o.TargetResourceType.IsSet()
}

// SetTargetResourceType sets field value
func (o *AuditRecord) SetTargetResourceType(v string) {
	o.TargetResourceType.Set(&v)
}

// GetTargetResourceId returns the TargetResourceId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AuditRecord) GetTargetResourceId() string {
	if o == nil || o.TargetResourceId.Get() == nil {
		var ret string
		return ret
	}

	return *o.TargetResourceId.Get()
}

// GetTargetResourceIdOk returns a tuple with the TargetResourceId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditRecord) GetTargetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TargetResourceId.Get(), o.TargetResourceId.IsSet()
}

// SetTargetResourceId sets field value
func (o *AuditRecord) SetTargetResourceId(v string) {
	o.TargetResourceId.Set(&v)
}

// GetMetadata returns the Metadata field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *AuditRecord) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditRecord) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *AuditRecord) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetProvenanceSource returns the ProvenanceSource field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AuditRecord) GetProvenanceSource() string {
	if o == nil || o.ProvenanceSource.Get() == nil {
		var ret string
		return ret
	}

	return *o.ProvenanceSource.Get()
}

// GetProvenanceSourceOk returns a tuple with the ProvenanceSource field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditRecord) GetProvenanceSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProvenanceSource.Get(), o.ProvenanceSource.IsSet()
}

// SetProvenanceSource sets field value
func (o *AuditRecord) SetProvenanceSource(v string) {
	o.ProvenanceSource.Set(&v)
}

// GetCorrelationId returns the CorrelationId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AuditRecord) GetCorrelationId() string {
	if o == nil || o.CorrelationId.Get() == nil {
		var ret string
		return ret
	}

	return *o.CorrelationId.Get()
}

// GetCorrelationIdOk returns a tuple with the CorrelationId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditRecord) GetCorrelationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CorrelationId.Get(), o.CorrelationId.IsSet()
}

// SetCorrelationId sets field value
func (o *AuditRecord) SetCorrelationId(v string) {
	o.CorrelationId.Set(&v)
}

func (o AuditRecord) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["record_id"] = o.RecordId
	toSerialize["event_id"] = o.EventId
	toSerialize["occurred_at"] = o.OccurredAt
	toSerialize["recorded_at"] = o.RecordedAt
	toSerialize["tenant_id"] = o.TenantId.Get()
	toSerialize["is_platform"] = o.IsPlatform
	toSerialize["actor_id"] = o.ActorId.Get()
	toSerialize["actor_kind"] = o.ActorKind.Get()
	toSerialize["action"] = o.Action
	toSerialize["outcome"] = o.Outcome
	toSerialize["target_resource_type"] = o.TargetResourceType.Get()
	toSerialize["target_resource_id"] = o.TargetResourceId.Get()
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["provenance_source"] = o.ProvenanceSource.Get()
	toSerialize["correlation_id"] = o.CorrelationId.Get()
	return toSerialize, nil
}

func (o *AuditRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"record_id",
		"event_id",
		"occurred_at",
		"recorded_at",
		"tenant_id",
		"is_platform",
		"actor_id",
		"actor_kind",
		"action",
		"outcome",
		"target_resource_type",
		"target_resource_id",
		"metadata",
		"provenance_source",
		"correlation_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuditRecord := _AuditRecord{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuditRecord)

	if err != nil {
		return err
	}

	*o = AuditRecord(varAuditRecord)

	return err
}

type NullableAuditRecord struct {
	value *AuditRecord
	isSet bool
}

func (v NullableAuditRecord) Get() *AuditRecord {
	return v.value
}

func (v *NullableAuditRecord) Set(val *AuditRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditRecord(val *AuditRecord) *NullableAuditRecord {
	return &NullableAuditRecord{value: val, isSet: true}
}

func (v NullableAuditRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
