/*
Credoxa Audit API

Public API contract for the Credoxa Audit service.  Authentication is provider-neutral. Consumers present an external bearer credential which is verified by the configured authentication adapter before Credoxa Audit establishes tenant/platform, actor, and capability authority.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaaudit

import (
	"encoding/json"
	"fmt"
)

// AuditOutcome the model 'AuditOutcome'
type AuditOutcome string

// List of AuditOutcome
const (
	AUDITOUTCOME_SUCCESS AuditOutcome = "success"
	AUDITOUTCOME_FAILURE AuditOutcome = "failure"
	AUDITOUTCOME_DENIED  AuditOutcome = "denied"
	AUDITOUTCOME_UNKNOWN AuditOutcome = "unknown"
)

// All allowed values of AuditOutcome enum
var AllowedAuditOutcomeEnumValues = []AuditOutcome{
	"success",
	"failure",
	"denied",
	"unknown",
}

func (v *AuditOutcome) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AuditOutcome(value)
	for _, existing := range AllowedAuditOutcomeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AuditOutcome", value)
}

// NewAuditOutcomeFromValue returns a pointer to a valid AuditOutcome
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAuditOutcomeFromValue(v string) (*AuditOutcome, error) {
	ev := AuditOutcome(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AuditOutcome: valid values are %v", v, AllowedAuditOutcomeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AuditOutcome) IsValid() bool {
	for _, existing := range AllowedAuditOutcomeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AuditOutcome value
func (v AuditOutcome) Ptr() *AuditOutcome {
	return &v
}

type NullableAuditOutcome struct {
	value *AuditOutcome
	isSet bool
}

func (v NullableAuditOutcome) Get() *AuditOutcome {
	return v.value
}

func (v *NullableAuditOutcome) Set(val *AuditOutcome) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditOutcome) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditOutcome) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditOutcome(val *AuditOutcome) *NullableAuditOutcome {
	return &NullableAuditOutcome{value: val, isSet: true}
}

func (v NullableAuditOutcome) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditOutcome) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
