/*
Credoxa Audit API

Public API contract for the Credoxa Audit service.  Authentication is provider-neutral. Consumers present an external bearer credential which is verified by the configured authentication adapter before Credoxa Audit establishes tenant/platform, actor, and capability authority.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaaudit

import (
	"encoding/json"
	"fmt"
)

// ActorKind the model 'ActorKind'
type ActorKind string

// List of ActorKind
const (
	ACTORKIND_HUMAN   ActorKind = "human"
	ACTORKIND_SERVICE ActorKind = "service"
	ACTORKIND_SYSTEM  ActorKind = "system"
)

// All allowed values of ActorKind enum
var AllowedActorKindEnumValues = []ActorKind{
	"human",
	"service",
	"system",
}

func (v *ActorKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ActorKind(value)
	for _, existing := range AllowedActorKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ActorKind", value)
}

// NewActorKindFromValue returns a pointer to a valid ActorKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewActorKindFromValue(v string) (*ActorKind, error) {
	ev := ActorKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ActorKind: valid values are %v", v, AllowedActorKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ActorKind) IsValid() bool {
	for _, existing := range AllowedActorKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ActorKind value
func (v ActorKind) Ptr() *ActorKind {
	return &v
}

type NullableActorKind struct {
	value *ActorKind
	isSet bool
}

func (v NullableActorKind) Get() *ActorKind {
	return v.value
}

func (v *NullableActorKind) Set(val *ActorKind) {
	v.value = val
	v.isSet = true
}

func (v NullableActorKind) IsSet() bool {
	return v.isSet
}

func (v *NullableActorKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActorKind(val *ActorKind) *NullableActorKind {
	return &NullableActorKind{value: val, isSet: true}
}

func (v NullableActorKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActorKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
